fix: next font is not exposed to whole app
ppdbultimate/design-system-moon pull request #26
Opened 2023-01-14 16:19 UTC by theodorusclarence

# Description & Technical Solution

Modal, with Modal.Section to customize items

# Checklist

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] Already rebased against main branch.

# Screenshots

https://user-images.githubusercontent.com/55318172/212482866-ccdd8046-2d5f-45c0-81ed-90ab95e4cbbf.mp4

2023-01-14 16:22 UTC, ppdbultimate commented
#### 📝 Changed routes:


| [**/_app.page**](https://design-system-moon-bxz6xk7s4-ppdbultimate.vercel.app/_app.page) | [**/index.page**](https://design-system-moon-bxz6xk7s4-ppdbultimate.vercel.app/index.page) |
|:-:|:-:|
|<a href="https://design-system-moon-bxz6xk7s4-ppdbultimate.vercel.app/_app.page"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/M-u7GPaa9nNpCGN4-DmTZYs5dAhwBC3YCi1cmXlhuYzugCUazcVcu5VnzQmQjFGwpp9GMywlSgPfoc-f-13hAg.png&w=600" alt="Screenshot of /_app.page" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/ZnCXVRO0pd1fk8ZanmCufn1EFpJHnalUge427Emab0vOdYBruQT4Jpc2-HPdGQWRwp3ixz-9eW6ha_uqX_Ndtg.png">(view full size)</a> |<a href="https://design-system-moon-bxz6xk7s4-ppdbultimate.vercel.app/index.page"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/5CVSifBQlKSIB-duAJ3B8fjRKEPzMh6Z9g9rkjRV5Oj-E2pK4W-ht1tJGbHSGvRlA17HsD_NpvxAZwR2rZZ6aQ.png&w=600" alt="Screenshot of /index.page" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/JhRItTobwDZGLFHWJ14QxpDLCtrb3N4hhc0oPIE66ChMVzeNW_bFDdthrL6Nq2ZS6P2rdYoxD2PG3oTlFNgRfw.png">(view full size)</a> |



| [**…omponents/ExampleModal**](https://design-system-moon-bxz6xk7s4-ppdbultimate.vercel.app/sandbox/components/ExampleModal) | [**/sandbox/modal.page**](https://design-system-moon-bxz6xk7s4-ppdbultimate.vercel.app/sandbox/modal.page) |
|:-:|:-:|
|<a href="https://design-system-moon-bxz6xk7s4-ppdbultimate.vercel.app/sandbox/components/ExampleModal"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/dEoN1pSD9v77Gs3W8JVs5eDe2Ax4o0C_wJcDUof45dLGYuOLtN8Zs7WDBHWSczt3jpf2uRsQfvySnEByGx_kuA.png&w=600" alt="Screenshot of /sandbox/components/ExampleModal" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/s8e6r6sqJYJZxaONeVH4gM5V3gsOWOITZV955qag125tG2WIYgUSG4UlG-CzjjBPRh-PMCTJcmxIgA1CXyUtFw.png">(view full size)</a> |<a href="https://design-system-moon-bxz6xk7s4-ppdbultimate.vercel.app/sandbox/modal.page"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/eyeVnjc1bpxCTtHlt5uurMK2RiIkJYHDJpr72hiB40CMqe0YSpORk2P4hNqifLT60ctYQNsZVZtouu0vhU72zQ.png&w=600" alt="Screenshot of /sandbox/modal.page" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/bt7fLkl-7tpY-b75mH9nd4ETfMLP9ubZaHbYutmUrjM5S3BnenY_iO0DbI3C0hg4Cr6Dv4OCbLa0zZgLIo2XIQ.png">(view full size)</a> |







Commit f1007e68576a0a05074053ab392bee22f6cf4f51 (https://design-system-moon-bxz6xk7s4-ppdbultimate.vercel.app).

2023-01-14 16:51 UTC, theodorusclarence commented
[fix: next font is not exposed to whole app](https://github.com/ppdbultimate/design-system-moon/pull/26/commits/6911acf6ad4ff843894edd4a1e823d0d6e41d7da)

kayaknya approach ini ada problem, karena tadi abis nyoba, dia pas initial visit ke page, malah jadi ga keload fontnya.
harus dicek lagi

2023-01-15 14:59 UTC, winatungmiharja commented on src/components/modal/Modal.tsx
> +      className={clsxm('flex w-full flex-col px-4 sm:px-6', 'py-6', className)}
perlu ditambahkan default `p-4 sm:p-6` mas? kalau defaultnya di mobile soalnya kurang simetris yang bagian section nya
<img width="176" alt="image" src="https://user-images.githubusercontent.com/64743796/212548784-1d0d9b52-2cbc-4cc5-b373-edb1f2703f49.png">

sedangkan bagian title nya baguss
![image](https://user-images.githubusercontent.com/64743796/212548796-3e75af15-781e-401a-9576-17bc48420e5c.png)

2023-01-15 15:39 UTC, winatungmiharja commented on src/components/modal/Modal.tsx
> +        className
ini kalau diubah jadi
`p-4 sm:p-6` gimana mas

2023-01-16 03:59 UTC, theodorusclarence commented on src/components/modal/Modal.tsx
> +        className
okee

2023-01-16 05:32 UTC, rizqitsani requested changes

2023-01-16 05:32 UTC, rizqitsani commented on src/pages/sandbox/components/ExampleModal.tsx
> +            <Button className='justify-center' variant='outline'>
ini gaperlu justify-center ce, di Button udah ada

2023-01-16 05:32 UTC, rizqitsani commented on src/pages/sandbox/components/ExampleModal.tsx
> +            <Button className='justify-center'>Label</Button>
ini juga

2023-01-16 07:04 UTC, winatungmiharja approved these changes

2023-01-16 08:35 UTC, rizqitsani approved these changes

2023-01-16 08:36 UTC, merged