feat: migrate dialog to radix
ppdbultimate/design-system-moon pull request #93
Opened 2024-01-19 14:35 UTC by snymnd

# Description & Technical Solution

Describe problems, if any, clearly and concisely.
Summarize the impact to the system.
Please also include relevant motivation and context.
Please include a summary of the technical solution and how it solves the problem.

# Checklist

- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] Already rebased against the main branch.

# Deployment Links To Test

Provide links to test the changes made.

# Screenshots

Provide screenshots or videos of the changes made if any.

2024-01-25 13:38 UTC, ppdbultimate commented
#### 📝 Changed routes:


| [**…s/ExampleAdaptiveModal**](https://design-system-moon-p272glp0d-ppdbultimate.vercel.app/sandbox/components/ExampleAdaptiveModal) |
|:-:|
|<a href="https://design-system-moon-p272glp0d-ppdbultimate.vercel.app/sandbox/components/ExampleAdaptiveModal"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/2a2SIfAkFWlwj7zXKyoGIwN_n3nfFEyp0gLjDl4Qr6JUlBYnjncxpJt8DyeE2doPuN0IO06Zx8HTKHJkkNiAzw.png&w=600" alt="Screenshot of /sandbox/components/ExampleAdaptiveModal" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/1r_U-ttIgb-0k_ZMGVbMqoiX6QW0RfNRZxDnzbPUWLJRtlT3x5ZtHaQ0DvCz9p-cOTek-5b3K0moKleezwiung.png">(view full size)</a> |







Commit 1fe7479e0b4c2d82e4ddd71cdcda9afbc6459904 (https://design-system-moon-p272glp0d-ppdbultimate.vercel.app).

2024-01-25 14:44 UTC, rizqitsani approved these changes

2024-01-25 17:51 UTC, winatungmiharja requested changes

2024-01-25 17:51 UTC, winatungmiharja commented on src/components/dialog/AlertDialog.tsx
> +      'px-4 sm:px-6 py-4',
```suggestion
      'px-4 sm:px-6 py-4 sm:py-6',
```
ini kelupaan nus
![Screenshot 2024-01-26 004328](https://github.com/ppdbultimate/design-system-moon/assets/64743796/f168b3e1-7ac7-4023-9da0-2d123ef26212)

2024-01-25 22:06 UTC, rizqitsani commented on src/components/dialog/AlertDialog.tsx
> +      'px-4 sm:px-6 py-4',
Jadi p-4 sm:p-6 aja ya wkwkwkwk

2024-01-26 06:20 UTC, snymnd commented on src/components/dialog/AlertDialog.tsx
> +      'px-4 sm:px-6 py-4',
done

2024-01-26 06:26 UTC, winatungmiharja approved these changes

2024-01-26 06:26 UTC, merged